home:
    path: /
    controller: App\Controller\Open\HomeController::index

about-us:
    path: /es/la-empresa
    controller: App\Controller\Open\HomeController::about_us

services:
    path: /es/servicios
    controller: App\Controller\Open\HomeController::services

contact:
    path: /es/contacto
    controller: App\Controller\Open\HomeController::contact

# zona privada
login:
    path: /login
    controller: App\Controller\UserController::login

tasks:
    path: /tareas
    controller: App\Controller\TaskController::index

task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail

tasks_creation:
    path: /tarea
    controller: App\Controller\TaskController::creation    

my_tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks  
    
task_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit

task_delete:
    path: /tarea/delete/{id}
    controller: App\Controller\TaskController::delete    

register:
    path: /registro
    controller: App\Controller\UserController::register
    
users:
    path: /users
    controller: App\Controller\UserController::index

logout:
    path: /logout
    # ya viene por defecto
    
    